apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: plugin-repo
  name: plugin-repo
  namespace: plugin-demo
spec:
  containers:
  - image: nginx:latest
    name: plugin-repo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: plugin-repo
  name: plugin-repo
  namespace: plugin-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: plugin-repo
  type: ClusterIP
status:
  loadBalancer: {}
